//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Компания.
    /// </summary>
    // *** Start programmer edit section *** (Компания CustomAttributes)

    // *** End programmer edit section *** (Компания CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КомпанияE", new string[] {
            "Название as \'Название\'",
            "Информация as \'Информация\'",
            "Ссылка as \'Ссылка\'",
            "ПрактикиИнфо as \'Практики инфо\'",
            "Практики as \'Практики\'"})]
    [View("КомпанияL", new string[] {
            "Название as \'Название\'",
            "Информация as \'Информация\'",
            "Ссылка as \'Ссылка\'",
            "ПрактикиИнфо as \'Практики инфо\'",
            "Практики as \'Практики\'"})]
    public class Компания : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fИнформация;
        
        private string fСсылка;
        
        private string fПрактикиИнфо;
        
        private bool fПрактики;
        
        // *** Start programmer edit section *** (Компания CustomMembers)

        // *** End programmer edit section *** (Компания CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Компания.Название CustomAttributes)

        // *** End programmer edit section *** (Компания.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Компания.Название Get start)

                // *** End programmer edit section *** (Компания.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Компания.Название Get end)

                // *** End programmer edit section *** (Компания.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Компания.Название Set start)

                // *** End programmer edit section *** (Компания.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Компания.Название Set end)

                // *** End programmer edit section *** (Компания.Название Set end)
            }
        }
        
        /// <summary>
        /// Информация.
        /// </summary>
        // *** Start programmer edit section *** (Компания.Информация CustomAttributes)

        // *** End programmer edit section *** (Компания.Информация CustomAttributes)
        [StrLen(255)]
        public virtual string Информация
        {
            get
            {
                // *** Start programmer edit section *** (Компания.Информация Get start)

                // *** End programmer edit section *** (Компания.Информация Get start)
                string result = this.fИнформация;
                // *** Start programmer edit section *** (Компания.Информация Get end)

                // *** End programmer edit section *** (Компания.Информация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Компания.Информация Set start)

                // *** End programmer edit section *** (Компания.Информация Set start)
                this.fИнформация = value;
                // *** Start programmer edit section *** (Компания.Информация Set end)

                // *** End programmer edit section *** (Компания.Информация Set end)
            }
        }
        
        /// <summary>
        /// Ссылка.
        /// </summary>
        // *** Start programmer edit section *** (Компания.Ссылка CustomAttributes)

        // *** End programmer edit section *** (Компания.Ссылка CustomAttributes)
        [StrLen(255)]
        public virtual string Ссылка
        {
            get
            {
                // *** Start programmer edit section *** (Компания.Ссылка Get start)

                // *** End programmer edit section *** (Компания.Ссылка Get start)
                string result = this.fСсылка;
                // *** Start programmer edit section *** (Компания.Ссылка Get end)

                // *** End programmer edit section *** (Компания.Ссылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Компания.Ссылка Set start)

                // *** End programmer edit section *** (Компания.Ссылка Set start)
                this.fСсылка = value;
                // *** Start programmer edit section *** (Компания.Ссылка Set end)

                // *** End programmer edit section *** (Компания.Ссылка Set end)
            }
        }
        
        /// <summary>
        /// ПрактикиИнфо.
        /// </summary>
        // *** Start programmer edit section *** (Компания.ПрактикиИнфо CustomAttributes)

        // *** End programmer edit section *** (Компания.ПрактикиИнфо CustomAttributes)
        [StrLen(255)]
        public virtual string ПрактикиИнфо
        {
            get
            {
                // *** Start programmer edit section *** (Компания.ПрактикиИнфо Get start)

                // *** End programmer edit section *** (Компания.ПрактикиИнфо Get start)
                string result = this.fПрактикиИнфо;
                // *** Start programmer edit section *** (Компания.ПрактикиИнфо Get end)

                // *** End programmer edit section *** (Компания.ПрактикиИнфо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Компания.ПрактикиИнфо Set start)

                // *** End programmer edit section *** (Компания.ПрактикиИнфо Set start)
                this.fПрактикиИнфо = value;
                // *** Start programmer edit section *** (Компания.ПрактикиИнфо Set end)

                // *** End programmer edit section *** (Компания.ПрактикиИнфо Set end)
            }
        }
        
        /// <summary>
        /// Практики.
        /// </summary>
        // *** Start programmer edit section *** (Компания.Практики CustomAttributes)

        // *** End programmer edit section *** (Компания.Практики CustomAttributes)
        public virtual bool Практики
        {
            get
            {
                // *** Start programmer edit section *** (Компания.Практики Get start)

                // *** End programmer edit section *** (Компания.Практики Get start)
                bool result = this.fПрактики;
                // *** Start programmer edit section *** (Компания.Практики Get end)

                // *** End programmer edit section *** (Компания.Практики Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Компания.Практики Set start)

                // *** End programmer edit section *** (Компания.Практики Set start)
                this.fПрактики = value;
                // *** Start programmer edit section *** (Компания.Практики Set end)

                // *** End programmer edit section *** (Компания.Практики Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КомпанияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомпанияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомпанияE", typeof(IIS.MyApp.Компания));
                }
            }
            
            /// <summary>
            /// "КомпанияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КомпанияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КомпанияL", typeof(IIS.MyApp.Компания));
                }
            }
        }
    }
}
