//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Курс.
    /// </summary>
    // *** Start programmer edit section *** (Курс CustomAttributes)

    // *** End programmer edit section *** (Курс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КурсE", new string[] {
            "Названиее as \'Названиее\'",
            "Подготовка as \'Подготовка\'",
            "Год as \'Год\'",
            "ОУ as \'ОУ\'",
            "ОУ.Название as \'Название\'"})]
    [View("КурсL", new string[] {
            "Названиее as \'Названиее\'",
            "Подготовка as \'Подготовка\'",
            "Год as \'Год\'",
            "ОУ.Название as \'Название\'"})]
    public class Курс : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниее;
        
        private string fПодготовка;
        
        private byte fГод;
        
        private IIS.Product_47130.ОУ fОУ;
        
        // *** Start programmer edit section *** (Курс CustomMembers)

        // *** End programmer edit section *** (Курс CustomMembers)

        
        /// <summary>
        /// Названиее.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Названиее CustomAttributes)

        // *** End programmer edit section *** (Курс.Названиее CustomAttributes)
        [StrLen(255)]
        public virtual string Названиее
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Названиее Get start)

                // *** End programmer edit section *** (Курс.Названиее Get start)
                string result = this.fНазваниее;
                // *** Start programmer edit section *** (Курс.Названиее Get end)

                // *** End programmer edit section *** (Курс.Названиее Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Названиее Set start)

                // *** End programmer edit section *** (Курс.Названиее Set start)
                this.fНазваниее = value;
                // *** Start programmer edit section *** (Курс.Названиее Set end)

                // *** End programmer edit section *** (Курс.Названиее Set end)
            }
        }
        
        /// <summary>
        /// Подготовка.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Подготовка CustomAttributes)

        // *** End programmer edit section *** (Курс.Подготовка CustomAttributes)
        [StrLen(255)]
        public virtual string Подготовка
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Подготовка Get start)

                // *** End programmer edit section *** (Курс.Подготовка Get start)
                string result = this.fПодготовка;
                // *** Start programmer edit section *** (Курс.Подготовка Get end)

                // *** End programmer edit section *** (Курс.Подготовка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Подготовка Set start)

                // *** End programmer edit section *** (Курс.Подготовка Set start)
                this.fПодготовка = value;
                // *** Start programmer edit section *** (Курс.Подготовка Set end)

                // *** End programmer edit section *** (Курс.Подготовка Set end)
            }
        }
        
        /// <summary>
        /// Год.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Год CustomAttributes)

        // *** End programmer edit section *** (Курс.Год CustomAttributes)
        public virtual byte Год
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Год Get start)

                // *** End programmer edit section *** (Курс.Год Get start)
                byte result = this.fГод;
                // *** Start programmer edit section *** (Курс.Год Get end)

                // *** End programmer edit section *** (Курс.Год Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Год Set start)

                // *** End programmer edit section *** (Курс.Год Set start)
                this.fГод = value;
                // *** Start programmer edit section *** (Курс.Год Set end)

                // *** End programmer edit section *** (Курс.Год Set end)
            }
        }
        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Курс.ОУ CustomAttributes)

        // *** End programmer edit section *** (Курс.ОУ CustomAttributes)
        public virtual IIS.Product_47130.ОУ ОУ
        {
            get
            {
                // *** Start programmer edit section *** (Курс.ОУ Get start)

                // *** End programmer edit section *** (Курс.ОУ Get start)
                IIS.Product_47130.ОУ result = this.fОУ;
                // *** Start programmer edit section *** (Курс.ОУ Get end)

                // *** End programmer edit section *** (Курс.ОУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.ОУ Set start)

                // *** End programmer edit section *** (Курс.ОУ Set start)
                this.fОУ = value;
                // *** Start programmer edit section *** (Курс.ОУ Set end)

                // *** End programmer edit section *** (Курс.ОУ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КурсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсE", typeof(IIS.Product_47130.Курс));
                }
            }
            
            /// <summary>
            /// "КурсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсL", typeof(IIS.Product_47130.Курс));
                }
            }
        }
    }
}
