//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Представитель ОУ.
    /// </summary>
    // *** Start programmer edit section *** (ПредставительОУ CustomAttributes)

    // *** End programmer edit section *** (ПредставительОУ CustomAttributes)
    [AutoAltered()]
    [Caption("Представитель ОУ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПредставительОУE", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "ОУ as \'ОУ\'",
            "ОУ.Название as \'Название\'"})]
    [View("ПредставительОУL", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "ОУ.Название as \'Название\'"})]
    public class ПредставительОУ : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private string fПочта;
        
        private string fТелефон;
        
        private string fДолжность;
        
        private IIS.MyApp.ОУ fОУ;
        
        // *** Start programmer edit section *** (ПредставительОУ CustomMembers)

        // *** End programmer edit section *** (ПредставительОУ CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Имя CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Имя Get start)

                // *** End programmer edit section *** (ПредставительОУ.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (ПредставительОУ.Имя Get end)

                // *** End programmer edit section *** (ПредставительОУ.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Имя Set start)

                // *** End programmer edit section *** (ПредставительОУ.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (ПредставительОУ.Имя Set end)

                // *** End programmer edit section *** (ПредставительОУ.Имя Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Почта CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Почта Get start)

                // *** End programmer edit section *** (ПредставительОУ.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (ПредставительОУ.Почта Get end)

                // *** End programmer edit section *** (ПредставительОУ.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Почта Set start)

                // *** End programmer edit section *** (ПредставительОУ.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (ПредставительОУ.Почта Set end)

                // *** End programmer edit section *** (ПредставительОУ.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Телефон CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Get start)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Get end)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Set start)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Set end)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Должность CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Должность Get start)

                // *** End programmer edit section *** (ПредставительОУ.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ПредставительОУ.Должность Get end)

                // *** End programmer edit section *** (ПредставительОУ.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Должность Set start)

                // *** End programmer edit section *** (ПредставительОУ.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ПредставительОУ.Должность Set end)

                // *** End programmer edit section *** (ПредставительОУ.Должность Set end)
            }
        }
        
        /// <summary>
        /// Представитель ОУ.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.ОУ CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.ОУ CustomAttributes)
        [PropertyStorage(new string[] {
                "ОУ"})]
        public virtual IIS.MyApp.ОУ ОУ
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.ОУ Get start)

                // *** End programmer edit section *** (ПредставительОУ.ОУ Get start)
                IIS.MyApp.ОУ result = this.fОУ;
                // *** Start programmer edit section *** (ПредставительОУ.ОУ Get end)

                // *** End programmer edit section *** (ПредставительОУ.ОУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.ОУ Set start)

                // *** End programmer edit section *** (ПредставительОУ.ОУ Set start)
                this.fОУ = value;
                // *** Start programmer edit section *** (ПредставительОУ.ОУ Set end)

                // *** End programmer edit section *** (ПредставительОУ.ОУ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПредставительОУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительОУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительОУE", typeof(IIS.MyApp.ПредставительОУ));
                }
            }
            
            /// <summary>
            /// "ПредставительОУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительОУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительОУL", typeof(IIS.MyApp.ПредставительОУ));
                }
            }
        }
    }
}
