//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Практика.
    /// </summary>
    // *** Start programmer edit section *** (Практика CustomAttributes)

    // *** End programmer edit section *** (Практика CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрактикаE", new string[] {
            "Информация as \'Информация\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "Состояние as \'Состояние\'",
            "ЗаявкаНаПрактику as \'Заявка на практику\'",
            "ЗаявкаНаПрактику.Информация as \'Информация\'",
            "Компания as \'Компания\'",
            "Компания.Название as \'Название\'"})]
    [View("ПрактикаL", new string[] {
            "Информация as \'Информация\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "Состояние as \'Состояние\'",
            "ЗаявкаНаПрактику.Информация as \'Информация\'",
            "Компания.Название as \'Название\'"})]
    public class Практика : ICSSoft.STORMNET.DataObject
    {
        
        private string fИнформация;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаКонца;
        
        private IIS.MyApp.СостояниеМероприятия fСостояние;
        
        private IIS.MyApp.ЗаявкаНаПрактику fЗаявкаНаПрактику;
        
        private IIS.MyApp.Компания fКомпания;
        
        // *** Start programmer edit section *** (Практика CustomMembers)

        // *** End programmer edit section *** (Практика CustomMembers)

        
        /// <summary>
        /// Информация.
        /// </summary>
        // *** Start programmer edit section *** (Практика.Информация CustomAttributes)

        // *** End programmer edit section *** (Практика.Информация CustomAttributes)
        [StrLen(255)]
        public virtual string Информация
        {
            get
            {
                // *** Start programmer edit section *** (Практика.Информация Get start)

                // *** End programmer edit section *** (Практика.Информация Get start)
                string result = this.fИнформация;
                // *** Start programmer edit section *** (Практика.Информация Get end)

                // *** End programmer edit section *** (Практика.Информация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.Информация Set start)

                // *** End programmer edit section *** (Практика.Информация Set start)
                this.fИнформация = value;
                // *** Start programmer edit section *** (Практика.Информация Set end)

                // *** End programmer edit section *** (Практика.Информация Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (Практика.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (Практика.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (Практика.ДатаНачала Get start)

                // *** End programmer edit section *** (Практика.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (Практика.ДатаНачала Get end)

                // *** End programmer edit section *** (Практика.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.ДатаНачала Set start)

                // *** End programmer edit section *** (Практика.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (Практика.ДатаНачала Set end)

                // *** End programmer edit section *** (Практика.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаКонца.
        /// </summary>
        // *** Start programmer edit section *** (Практика.ДатаКонца CustomAttributes)

        // *** End programmer edit section *** (Практика.ДатаКонца CustomAttributes)
        public virtual System.DateTime ДатаКонца
        {
            get
            {
                // *** Start programmer edit section *** (Практика.ДатаКонца Get start)

                // *** End programmer edit section *** (Практика.ДатаКонца Get start)
                System.DateTime result = this.fДатаКонца;
                // *** Start programmer edit section *** (Практика.ДатаКонца Get end)

                // *** End programmer edit section *** (Практика.ДатаКонца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.ДатаКонца Set start)

                // *** End programmer edit section *** (Практика.ДатаКонца Set start)
                this.fДатаКонца = value;
                // *** Start programmer edit section *** (Практика.ДатаКонца Set end)

                // *** End programmer edit section *** (Практика.ДатаКонца Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Практика.Состояние CustomAttributes)

        // *** End programmer edit section *** (Практика.Состояние CustomAttributes)
        public virtual IIS.MyApp.СостояниеМероприятия Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Практика.Состояние Get start)

                // *** End programmer edit section *** (Практика.Состояние Get start)
                IIS.MyApp.СостояниеМероприятия result = this.fСостояние;
                // *** Start programmer edit section *** (Практика.Состояние Get end)

                // *** End programmer edit section *** (Практика.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.Состояние Set start)

                // *** End programmer edit section *** (Практика.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Практика.Состояние Set end)

                // *** End programmer edit section *** (Практика.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Практика.
        /// </summary>
        // *** Start programmer edit section *** (Практика.ЗаявкаНаПрактику CustomAttributes)

        // *** End programmer edit section *** (Практика.ЗаявкаНаПрактику CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаявкаНаПрактику"})]
        [NotNull()]
        public virtual IIS.MyApp.ЗаявкаНаПрактику ЗаявкаНаПрактику
        {
            get
            {
                // *** Start programmer edit section *** (Практика.ЗаявкаНаПрактику Get start)

                // *** End programmer edit section *** (Практика.ЗаявкаНаПрактику Get start)
                IIS.MyApp.ЗаявкаНаПрактику result = this.fЗаявкаНаПрактику;
                // *** Start programmer edit section *** (Практика.ЗаявкаНаПрактику Get end)

                // *** End programmer edit section *** (Практика.ЗаявкаНаПрактику Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.ЗаявкаНаПрактику Set start)

                // *** End programmer edit section *** (Практика.ЗаявкаНаПрактику Set start)
                this.fЗаявкаНаПрактику = value;
                // *** Start programmer edit section *** (Практика.ЗаявкаНаПрактику Set end)

                // *** End programmer edit section *** (Практика.ЗаявкаНаПрактику Set end)
            }
        }
        
        /// <summary>
        /// Практика.
        /// </summary>
        // *** Start programmer edit section *** (Практика.Компания CustomAttributes)

        // *** End programmer edit section *** (Практика.Компания CustomAttributes)
        [PropertyStorage(new string[] {
                "Компания"})]
        public virtual IIS.MyApp.Компания Компания
        {
            get
            {
                // *** Start programmer edit section *** (Практика.Компания Get start)

                // *** End programmer edit section *** (Практика.Компания Get start)
                IIS.MyApp.Компания result = this.fКомпания;
                // *** Start programmer edit section *** (Практика.Компания Get end)

                // *** End programmer edit section *** (Практика.Компания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Практика.Компания Set start)

                // *** End programmer edit section *** (Практика.Компания Set start)
                this.fКомпания = value;
                // *** Start programmer edit section *** (Практика.Компания Set end)

                // *** End programmer edit section *** (Практика.Компания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрактикаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрактикаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрактикаE", typeof(IIS.MyApp.Практика));
                }
            }
            
            /// <summary>
            /// "ПрактикаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрактикаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрактикаL", typeof(IIS.MyApp.Практика));
                }
            }
        }
    }
}
