//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние мероприятия.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеМероприятия CustomAttributes)

    // *** End programmer edit section *** (СостояниеМероприятия CustomAttributes)
    public enum СостояниеМероприятия
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеМероприятия.ЗаявкаПодтверждена CustomAttributes)

        // *** End programmer edit section *** (СостояниеМероприятия.ЗаявкаПодтверждена CustomAttributes)
        ЗаявкаПодтверждена,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеМероприятия.Впроцессе CustomAttributes)

        // *** End programmer edit section *** (СостояниеМероприятия.Впроцессе CustomAttributes)
        Впроцессе,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеМероприятия.Завершена CustomAttributes)

        // *** End programmer edit section *** (СостояниеМероприятия.Завершена CustomAttributes)
        Завершена,
    }
}
