//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSEEntities : DbContext
    {
        public HSEEntities()
            : base("name=HSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLog> ApplicationLog { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<STORMAC> STORMAC { get; set; }
        public virtual DbSet<STORMAdvLimit> STORMAdvLimit { get; set; }
        public virtual DbSet<STORMAG> STORMAG { get; set; }
        public virtual DbSet<STORMF> STORMF { get; set; }
        public virtual DbSet<STORMFILTERDETAIL> STORMFILTERDETAIL { get; set; }
        public virtual DbSet<STORMFILTERLOOKUP> STORMFILTERLOOKUP { get; set; }
        public virtual DbSet<STORMFILTERSETTING> STORMFILTERSETTING { get; set; }
        public virtual DbSet<STORMI> STORMI { get; set; }
        public virtual DbSet<STORMLA> STORMLA { get; set; }
        public virtual DbSet<STORMLG> STORMLG { get; set; }
        public virtual DbSet<STORMLO> STORMLO { get; set; }
        public virtual DbSet<STORMLR> STORMLR { get; set; }
        public virtual DbSet<STORMLV> STORMLV { get; set; }
        public virtual DbSet<STORMNETLOCKDATA> STORMNETLOCKDATA { get; set; }
        public virtual DbSet<STORMP> STORMP { get; set; }
        public virtual DbSet<STORMS> STORMS { get; set; }
        public virtual DbSet<STORMSETTINGS> STORMSETTINGS { get; set; }
        public virtual DbSet<STORMWEBSEARCH> STORMWEBSEARCH { get; set; }
        public virtual DbSet<UserSetting> UserSetting { get; set; }
        public virtual DbSet<ЗаявкаНаПрактику> ЗаявкаНаПрактику { get; set; }
        public virtual DbSet<Компания> Компания { get; set; }
        public virtual DbSet<Курс> Курс { get; set; }
        public virtual DbSet<ОУ> ОУ { get; set; }
        public virtual DbSet<Практика> Практика { get; set; }
        public virtual DbSet<ПредставительКомпании> ПредставительКомпании { get; set; }
        public virtual DbSet<ПредставительОУ> ПредставительОУ { get; set; }
        public virtual DbSet<Студент> Студент { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
