//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORMAG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORMAG()
        {
            this.STORMI = new HashSet<STORMI>();
            this.STORMI1 = new HashSet<STORMI>();
            this.STORMLG = new HashSet<STORMLG>();
            this.STORMLG1 = new HashSet<STORMLG>();
            this.STORMLR = new HashSet<STORMLR>();
            this.STORMLR1 = new HashSet<STORMLR>();
            this.STORMP = new HashSet<STORMP>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Pwd { get; set; }
        public bool IsUser { get; set; }
        public bool IsGroup { get; set; }
        public bool IsRole { get; set; }
        public string ConnString { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string Editor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMI> STORMI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMI> STORMI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMLG> STORMLG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMLG> STORMLG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMLR> STORMLR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMLR> STORMLR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORMP> STORMP { get; set; }
    }
}
