//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORMAC
    {
        public System.Guid primaryKey { get; set; }
        public string TypeAccess { get; set; }
        public Nullable<System.Guid> Filter_m0 { get; set; }
        public System.Guid Permition_m0 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string Editor { get; set; }
    
        public virtual STORMF STORMF { get; set; }
        public virtual STORMP STORMP { get; set; }
    }
}
