//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORMFILTERLOOKUP
    {
        public System.Guid primaryKey { get; set; }
        public string DataObjectType { get; set; }
        public string Container { get; set; }
        public string ContainerTag { get; set; }
        public string FieldsToView { get; set; }
        public System.Guid FilterSetting_m0 { get; set; }
    
        public virtual STORMFILTERSETTING STORMFILTERSETTING { get; set; }
    }
}
