//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORMSETTINGS
    {
        public System.Guid primaryKey { get; set; }
        public string Module { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string User { get; set; }
    }
}
