//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Курс
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Курс()
        {
            this.Студент = new HashSet<Студент>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Названиее { get; set; }
        public string Подготовка { get; set; }
        public Nullable<byte> Год { get; set; }
        public Nullable<System.Guid> ОУ { get; set; }
    
        public virtual ОУ ОУ1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент> Студент { get; set; }
    }
}
