//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставительКомпании
    {
        public System.Guid primaryKey { get; set; }
        public string Имя { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string Должность { get; set; }
        public Nullable<System.Guid> Компания { get; set; }
    
        public virtual Компания Компания1 { get; set; }
    }
}
